links:
  consume:
    - auto: false
      min: 1
      max: 1
      role: g8os_client
      argname: client
    - auto: false
      min: 1
      max: 1
      role: grid_config
      argname: gridConfig
